### ISSUE TITLE
#error "Dunno about this gcc" when using gcc version greater than 8

### ISSUE THREAD

**Issue by pierre33** [CNES/cars#2]
ITK 4-13 cannot support gcc and g++ versions > 8.

I had to patch the file include/ITK-4.13/vcl_compiler.h to achieve the compilation of CARS by adding directive when gcc version is equal to 9.

**Comment by duboise-cnes** [comment]
Thanks @pierre33 for the information. As said, The problem comes from ITK gcc dependencies with OTB installation and dependencies in CARS.  To make it work, a good way is also to be able to have several compilers in your system with update-alternatives tool. Please follow : https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa if you want several compilers version and be compatible and adapt depending on tools.
